// src/components/applications/levelOne/index.vue
<template>
  <div class='wrap' >
  
	<section class='left'>
		<img :src='pic' />
	</section>
	<section class='right'>
		<p class='title' style="margin-bottom: 20px;margin-top: -20px;font-weight: 600;">Brief Introduction of the Project</p>
		<p v-for="(item,i) in content"  :class="i%2==0?'title':'normalContent'">{{item}}</p>
	</section>
  </div>
</template>
<script>
	import { get } from '@/axios/fetch';
    export default {
      name: 'applications',
      data () {
        return {
			pic:'/static/image/applications/levelOne/',
			content:[],
        }
      },
      mounted(){
		  this.pic += this.$route.query.id+'.png';
		  this.getContent();
      },
      methods:{
		 getContent(){
			 let textPath = '/static/js/applications/levelOne/'+this.$route.query.id+'.json'
			get(textPath).then((res)=>{
				console.log('resddd',res)
			  this.content = res.arr;
			})
		 },
      }
    }
</script>
<style scoped lang='less'>
	@import "./index.less";
</style>

// src/components/products/levelOne/index.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import {get} from '../../../axios/index.js';
import less from './index.less'
export default class LevelOne extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            picNum: 0,
            picArr: [],
            basePath: '/static/image/products/levelOne/',
        }
    }
    render() {
        console.log(this.props)
        return (
            <div className={less.wrap}>
                <div className={less.container1}>
                    <section className={less.pic}>
                        <ul >
                            {
                                this.state.picArr.map((item, i) => {
                                    return (
                                        <li key={i}>
                                            <Link to={`/products/levelTwo/${this.props.match.params.name}/${this.props.match.params.id}`}>
                                                <div className={less.img_pic} >
                                                    <img src={item.piclink} />
                                                </div>
                                            </Link>
                                        </li>
                                    )
                                })
                            }
                        </ul>
                    </section>
                </div>
            </div>
        );
    }
    componentWillMount(){
        this.operatorData();  
    }
    operatorData(){
        let path = this.state.basePath + this.props.match.params.name+'/imageMsg.json';
        get(path).then((res)=>{
             let arr = [];
            for(let i=0;i<res.picNum;i++){
                arr.push({
               piclink:this.state.basePath + this.props.match.params.name +'/' + (i+1)+'.png',
               routerPath:{path:'/products/levelTwo/'+ this.props.match.params.name +'/' + (i+1)},
               })
            };
            this.setState({
                picNum:res.picNum,
                picArr:arr
            })
        })
    } 
}
