// src/components/applications/detail/index.jsx
import React from 'react';
import {get} from '../../../axios/index.js';
import less from './index.less';
export default class Detail extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            pic: '/static/image/applications/levelOne/',
            content: ['test','test12323'],
        }
    }
    componentWillMount(){
        this.getContent();
    }
    render() {
        return (
            <div className={less.wrap} >
                <section className={less.left}>
                    <img src={`${this.state.pic}/${this.props.match.params.id}.png`} />
                </section>
                <section className={less.right}>
                    <p className={less.title} style={{ marginBottom: 20, marginTop: -20, fontWeight: 600 }}> Brief Introduction of the Project</p>
                    {
                        this.state.content.map((item, i) => {
                           return (
                            <p key={i} className={i % 2 == 0 ? less.title: less.normalContent}>{item}</p>
                           ) 
                        })
                    }
                </section>
            </div>
        )
    }
    getContent(){
    let textPath = '/static/js/applications/levelOne/'+this.props.match.params.id+'.json'
       get(textPath).then((res)=>{
           this.setState({
            content:res.arr 
           })
           console.log('content',this.state.content)
       })
    }
}

// src/components/applications/detail/index.vue
<template>
  <div class='wrap' >
	<section class='left'>
		<img :src='pic' />
	</section>
	<section class='right'>
		<p class='title' style="margin-bottom: 20px;margin-top: -20px;font-weight: 600;">Brief Introduction of the Project</p>
		<p v-for="(item,i) in content"  :class="i%2==0?'title':'normalContent'">{{item}}</p>
	</section>
  </div>
</template>
<script>
	import { get } from '@/axios/fetch';
    export default {
      name: 'applications',
      data () {
        return {
			pic:'/static/image/applications/levelOne/',
			content:[],
        }
      },
      mounted(){
		  this.pic += this.$route.query.id+'.png';
		  this.getContent();
      },
      methods:{
		 getContent(){
			 let textPath = '/static/js/applications/levelOne/'+this.$route.query.id+'.json'
			get(textPath).then((res)=>{
				console.log('resddd',res)
			  this.content = res.arr;
			})
		 },
      }
    }
</script>
<style scoped lang='less'>
	@import "./index.less";
</style>
