// src/components/contacts/index.vue
<template>
  <div class='wrap'>
	  <ul>
		  <li class='left'>
			  <p class='' v-for='item in address'>
			  	   {{item}}
			  </p>
			  <br />
			  <p v-for='item in email'>
			  	   {{item}}
			  </p>
		  </li>
		   <li class='right'>
			   <img src='static/image/contact/1.png' />
		   </li>
	  </ul>
  </div>
</template>
<script>

    export default {
      name: 'about',
      components:{

      },
      data () {
        return {
			address:[
				'Registered Office Add.:' ,
				'B906, Nanfang Building, Luofang Rd.', 
				'Luohu Dist., Shenzhen, China',
				'Zip Code: 518000',
				'Company Tel.: +86 755 826837760',
			],
			email:[
				'E-mail:',
				'info@star-an.com',
				'ying@star-an.com',
				'vp@star-an.com',
			],
			
        }
      },
      mounted(){

      },

      methods:{
      }
    }
</script>
<style scoped lang='less'>
	ul {
		display: flex;
	    flex-direction: row;
		
		li{
			img{
				height: 330px;
				width:525px;
			}
		}
		li.left{
			p{
				height:30px ;
				line-height: 30px;
				font-size: 16px;
			}
		}
		li.right{
			margin-left: 70px;
		}
	}
</style>

// src/components/contacts/index.jsx
import React from 'react';
import less from './index.less';
export default class Contacts extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            address: [
                'Registered Office Add.:',
                'B906, Nanfang Building, Luofang Rd.',
                'Luohu Dist., Shenzhen, China',
                'Zip Code: 518000',
                'Company Tel.: +86 755 826837760',
            ],
            email: [
                'E-mail:',
                'info@star-an.com',
                'ying@star-an.com',
                'vp@star-an.com',
            ],
        }
    }
    render() {
        return (
            <div class={less.wrap}>
                <ul>
                    <li className={less.left}>
                        {
                             this.state.address.map((item,i)=>{
                                return (
                                    <p key={i}>{item}</p>
                                )
                            })
                        }
                       
                        <br />
                        {
                            this.state.email.map((item,i)=>{
                                return (
                                <p key={i}>{item}</p>
                                )
                            })
                        }
                      
                    </li>
                    <li className={less.right}>
                        <img src='static/image/contact/1.png' />
                    </li>
                </ul>
            </div>
        );
    }
}
